<div id="div-communaute">
	<h1>La communauté</h1>
	<table id="table-communaute" class="table">

		<thead>
			<tr>
				<th>Position</th>
				<th>Nom joueur</th>
				<th>Score</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>Doe</td>
				<td>23000</td>
			</tr>
			<tr>
				<td>2</td>
				<td>Moe</td>
				<td>20500</td>
			</tr>
			<tr>
				<td>3</td>
				<td>Quelqu'un</td>
				<td>18000</td>
			</tr>
			<tr>
				<td>4</td>
				<td>D'autre</td>
				<td>16500</td>
			</tr>
			<tr>
				<td>5</td>
				<td>Doe</td>
				<td>16000</td>
			</tr>
			<tr>
				<td>6</td>
				<td>Moe</td>
				<td>14500</td>
			</tr>
			<tr>
				<td>7</td>
				<td>Quelqu'un</td>
				<td>13000</td>
			</tr>
			<tr>
				<td>8</td>
				<td>D'autre</td>
				<td>12700</td>
			</tr>
			<tr>
				<td>9</td>
				<td>Doe</td>
				<td>12400</td>
			</tr>
			<tr>
				<td>10</td>
				<td>Moe</td>
				<td>11000</td>
			</tr>
			<tr>
				<td>11</td>
				<td>Quelqu'un</td>
				<td>10500</td>
			</tr>
			<tr>
				<td>12</td>
				<td>D'autre</td>
				<td>10100</td>
			</tr>
			<tr>
				<td>13</td>
				<td>Doe</td>
				<td>9000</td>
			</tr>
			<tr>
				<td>14</td>
				<td>Moe</td>
				<td>8600</td>
			</tr>
			<tr>
				<td>15</td>
				<td>Quelqu'un</td>
				<td>8000</td>
			</tr>
			<tr>
				<td>16</td>
				<td>D'autre</td>
				<td>3000</td>
			</tr>
		</tbody>
	</table>
</div>